[phases.setup]
nixPkgs = ["jdk21"]

[phases.build]
cmds = [
  "chmod +x gradlew",
  "./gradlew clean build -x test --no-daemon"
]

[start]
cmd = "java -Duser.timezone=America/Chicago -Dserver.port=$PORT -jar tc-server/build/libs/timeclock.jar"
