[phases.setup]
nixPkgs = ["nodejs", "gradle"]

[phases.build]
cmds = [
  "chmod +x gradlew",
  "./gradlew build -x test"
]

[start]
cmd = "java $JAVA_OPTS -Dserver.port=$PORT -jar tc-server/build/libs/timeclock.jar"
